### ISSUE TITLE
实现红色导航条动画+名字长度随机的按钮

### ISSUE THREAD

**Issue by liuxuan30** [lizelu/SliderTabBar#1]
我想问一下，如果那个‘按钮X’的名字是随机长度，可长可短，参考安卓的APP Store的那个风格，能否实现这样的效果？

**Comment by lizelu** [comment]
可以实现的~固定字体，计算一下文字的宽度来设定button的宽度即可~

**Comment by liuxuan30** [comment]
你能否实现一个？我自己实现了一个，动画效果不太理想。想看看大牛怎么实现的。我感觉到得难点是
